version: 2.1
workflows:
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
jobs:
  test:
    docker:
      - image: golang:1.18.0
    steps:
      - checkout
